//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Borealis.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participants
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string RaceTime { get; set; }
        public System.DateTime DateTimeRegistered { get; set; }
        public Nullable<System.DateTime> DateTimeAccepted { get; set; }
    }
}
